### ISSUE TITLE
Documentation/README

### ISSUE THREAD

**Issue by vandlol** [aburgueno/lego-collection#5]
Please extend your README - since you expect users to create a file called rebrickable_credentials but you never even describe what this should contain.

Would really like to use your Project, maybe even help/extend.

Cheers

**Comment by aburgueno** [comment]
Hi there! thank you for raising this issue! I have slightly improved the README file hoping to give enough information to get you started. Please let me know if you need further assistance. I will be happy to discuss with your further improvements to this piece of software. Best wishes!
